## CHANGE this to the name of your plugin.
name: projectId

## CHANGE this to your username.
author: goudan

## CHANGE this to a meaninful but short description of your plugin.
description: This is exclusive to addicted servers

## CHANGE this to the path of the class that extends JavaPlugin.
main: groupId.projectId.projectId

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
